on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: go run main.go > index.md
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -u
        git commit -m "Update index.md"
        git push
