on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go run main.go > index.md
      - run: go install github.com/hoffa/pt@latest
      - run: ~/go/bin/pt < index.md > index.html
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m Publish
          git push
